controller_list:
  - name: ""
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_arm_tilt_joint
      - right_arm_lift_joint
      - right_arm_rotate_joint
      - right_arm_elbow_joint
      - right_arm_wrist_tilt_joint
      - right_arm_wrist_pan_joint

  - name: right_gripper
    type: GripperCommand
    action_ns: gripper_action
    default: true
    joints:
      - right_arm_gripper_joint

  - name: head_controller
    type: FollowJointTrajectory
    action_ns: head_trajectory
    joints:
      - head_tilt_mod_joint
      - head_pan_joint
      
