controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_arm_tilt_joint
      - right_arm_lift_joint
      - right_arm_rotate_joint
      - right_arm_elbow_joint
      - right_arm_wrist_pan_joint
      - right_arm_wrist_tilt_joint
  - name: fake_right_gripper_controller
    joints:
      - right_arm_gripper_joint
  - name: fake_head_controller
    joints:
      - head_tilt_mod_joint
      - head_pan_joint